/*Creando la BD con la codificación correcta*/
CREATE DATABASE aula_cw CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
/*Ideas: 
cambiar los tipos de ID de INT a SMALLINT 
aplicar la restricción default*/

/*Creando la tabla ESTADO*/ 
/*Esta ya está lista*/
CREATE TABLE ESTADO(
    ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    estado VARCHAR(25)    
);

/*Esta es la tabla GRADO*/ 
CREATE TABLE GRADO(
    ID_GRADO TINYINT PRIMARY KEY,
    grado VARCHAR(6) UNIQUE
);

/*Esta es la tabla CICLOS*/
/*En duda*/
CREATE TABLE CICLOS(
    ID_CICLOS SMALLINT PRIMARY KEY AUTO_INCREMENT,
    ciclos CHAR(20) 
);

/*Esta es la tabla PRIVACIDAD*/
CREATE TABLE PRIVACIDAD(
    ID_PRIV TINYINT PRIMARY KEY, 
    privacidad CHAR(25)
); 

/*Esta es la tabla MATERIAS*/
CREATE TABLE MATERIAS(
    ID_MATERIAS TINYINT PRIMARY KEY, 
    materias CHAR(50)
); 

/*Esta es la tabla ROL_USER*/
CREATE TABLE ROL_USER(
    ID_ROL TINYINT PRIMARY KEY,
    rol CHAR(50) 
);

/*Esta es la tabla GRUPO*/
CREATE TABLE GRUPO(
    ID_GRUPO SMALLINT PRIMARY KEY, 
    grupo SMALLINT UNIQUE
);

/*Esta es la tabla TIPO_ASIGN*/
CREATE TABLE TIPO_ASIGN(
    ID_TIPO_ASIGN TINYINT PRIMARY KEY, 
    tipo_asign CHAR(25)
);

/*Esta es la tabla ESTADO_ENTREGA*/
CREATE TABLE(
    ID_ESTADO_ENTREGA TINYINT PRIMARY KEY, 
    estado CHAR(50) 
);

/*Esta es la tabla TIPO_USER*/
CREATE TABLE TIPO_USER(
    ID_TIPO_USER INT PRIMARY KEY, 
    estado VARCHAR(25)
);


/*Esta es la tabla TIPO_AULA*/
/*Esta tiene una FK*/
CREATE TABLE TIPO_AULA(
    ID_TIPO_AULA TINYINT PRIMARY KEY, 
    ID_PRIV TINYINT,
    FOREIGN KEY(ID_PRIV) REFERENCES PRIVACIDAD(ID_PRIV),
    tipo CHAR(15)
);

/*Esta es la tabla AULA*/
/*Tiene FKs */
CREATE TABLE AULA(
    ID_AULA CHAR(50),
    ID_MATERIAS TINYINT,
    ID_GRUPO SMALLINT,
    ID_CICLOS SMALLINT /*AUTO_INCREMENT*/, 
    ID_GRADO TINYINT, 
    ID_TIPO_AULA TINYINT,
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS),
    FOREIGN KEY(ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    FOREIGN KEY(ID_CICLOS) REFERENCES CICLOS(ID_CICLOS),
    FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO), 
    nombre CHAR(50),
    reuniones_id CHAR(250),
    descripcion CHAR(250), 
    ruta foto CHAR(50),
    seccion VARCHAR(1)   
);

/*Esta es la tabla USUARIO*/
/*Tiene FKs*/
CREATE TABLE USUARIO(
    ID_USUARIO INT PRIMARY KEY, 
    ID_ESTADO INT /*Auto increment*/,
    ID_TIPO_USER INT, 
    ID_GRADO TINYINT, 
    FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    FOREIGN KEY(ID_TIPO_USER) REFERENCES TIPO_USER(ID_TIPO_USER),
    FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO),
    nombre CHAR(50),
    apodo CHAR(50) UNIQUE, 
    apellido_paterno CHAR(50),
    apellido_materno CHAR(50), 
    num_identificador INT UNIQUE, 
    correo CHAR(80) UNIQUE, 
    ruta_foto CHAR(50), 
    estado_unico CHAR(50),
    teléfono INT
);

/*Esta es la tabla Aula has Usuario*/
/*Tiene FKs */
CREATE TABLE AULAHASUSUARIO(
    ID_AHU INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, 
    ID_AULA CHAR(50),
    ID_ROL TINYINT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    FOREIGN KEY(ID_ROL) REFERENCES ROL_USER(ID_ROL)
);




