/*Creando la BD con la codificación correcta*/
-- CREATE DATABASE aula_cw CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;



CREATE TABLE ESTADO(
    ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT, 
    estado VARCHAR(25)    
);

 
CREATE TABLE GRADO(
    ID_GRADO TINYINT PRIMARY KEY AUTO_INCREMENT,
    grado VARCHAR(8) UNIQUE
);


CREATE TABLE CICLOS(
    ID_CICLOS SMALLINT PRIMARY KEY AUTO_INCREMENT,
    ciclos CHAR(20) 
);


CREATE TABLE PRIVACIDAD(
    ID_PRIV TINYINT PRIMARY KEY AUTO_INCREMENT, 
    privacidad CHAR(25)
); 


CREATE TABLE TIPO_MAT(
    ID_TIPO_MAT TINYINT PRIMARY KEY,
    tipomat CHAR(70)
);


CREATE TABLE MATERIAS(
    ID_MATERIAS TINYINT PRIMARY KEY, 
    materias CHAR(50), 
    ID_GRADO TINYINT, 
    FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO),
    ID_TIPO_MAT TINYINT, 
    FOREIGN KEY(ID_TIPO_MAT) REFERENCES TIPO_MAT(ID_TIPO_MAT) 
); 


ALTER TABLE MATERIAS ADD ID_GRADO TINYINT;
ALTER TABLE MATERIAS ADD ID_TIPO_MAT TINYINT;
ALTER TABLE MATERIAS ADD FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO);
ALTER TABLE MATERIAS ADD FOREIGN KEY(ID_TIPO_MAT) REFERENCES TIPO_MAT(ID_TIPO_MAT);


CREATE TABLE ROL_USER(
    ID_ROL TINYINT PRIMARY KEY AUTO_INCREMENT, 
    rol CHAR(50) 
);


CREATE TABLE GRUPO(
    ID_GRUPO SMALLINT PRIMARY KEY, 
    grupo SMALLINT UNIQUE
);

CREATE TABLE TIPO_ASIGN(
    ID_TIPO_ASIGN TINYINT PRIMARY KEY AUTO_INCREMENT, 
    tipo_asign CHAR(25) 
);

CREATE TABLE ESTADO_ENTREGA(
    ID_ESTADO_ENTREGA TINYINT PRIMARY KEY AUTO_INCREMENT,  
    estado CHAR(50) 
);


CREATE TABLE TIPO_USER(
    ID_TIPO_USER INT PRIMARY KEY, 
    tipo_usuario VARCHAR(25)
);


CREATE TABLE TIPO_AULA(
    ID_TIPO_AULA TINYINT PRIMARY KEY, 
    tipo CHAR(50),
    ID_PRIV TINYINT,
    FOREIGN KEY(ID_PRIV) REFERENCES PRIVACIDAD(ID_PRIV),
    
);


CREATE TABLE AULA(
    ID_AULA CHAR(50) PRIMARY KEY, 
    ID_MATERIAS TINYINT,
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS),
    ID_GRUPO SMALLINT,
    FOREIGN KEY(ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    ID_CICLOS SMALLINT /*AUTO_INCREMENT*/, 
    FOREIGN KEY(ID_CICLOS) REFERENCES CICLOS(ID_CICLOS),
    ID_GRADO TINYINT, 
    FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO), 
    ID_TIPO_AULA TINYINT,
    FOREIGN KEY(ID_TIPO_AULA) REFERENCES TIPO_AULA(ID_TIPO_AULA),
    nombre CHAR(50),
    reuniones_id CHAR(250),
    descripcion CHAR(250), 
    ruta_foto CHAR(50),
    seccion VARCHAR(1)   
);


CREATE TABLE USUARIO(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT, 
    ID_ESTADO INT /*Auto increment*/,
    FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    ID_TIPO_USER INT, 
    FOREIGN KEY(ID_TIPO_USER) REFERENCES TIPO_USER(ID_TIPO_USER),
    ID_GRADO TINYINT, 
    FOREIGN KEY(ID_GRADO) REFERENCES GRADO(ID_GRADO),
    nombre CHAR(50),
    apodo CHAR(50) UNIQUE, 
    apellido_paterno CHAR(50),
    apellido_materno CHAR(50), 
    num_identificador CHAR(13) UNIQUE, /*Change*/
    correo CHAR(80) UNIQUE, 
    ruta_foto CHAR(50),     
    estado_unico CHAR(50),
    telefono INT,
    password CHAR(30)
);


CREATE TABLE AULA_HAS_USUARIO(
    ID_AHU INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_AULA CHAR(50),
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    ID_ROL TINYINT, 
    FOREIGN KEY(ID_ROL) REFERENCES ROL_USER(ID_ROL)
    
);


CREATE TABLE USUARIO_HAS_INTERESES(
    ID_UHI INT PRIMARY KEY AUTO_INCREMENT, 
    ID_MATERIAS TINYINT, 
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS), 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) 
);

CREATE TABLE USUARIO_HAS_INSIGNIAS(
    ID_USUARIO_HAS_INSIGNIAS INT PRIMARY KEY AUTO_INCREMENT, 
    ID_MATERIAS TINYINT, 
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS), 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO), 
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA), 
    nombre_insignia CHAR(50) 
);


CREATE TABLE BLOQUE(
    ID_BLOQUE TINYINT PRIMARY KEY AUTO_INCREMENT, 
    ruta_foto CHAR(250), 
    titulo CHAR(60) NOT NULL,
    descripcion TEXT,  
    ID_AULA CHAR(50),
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA)
);


CREATE TABLE TEMA(
    ID_TEMA TINYINT PRIMARY KEY AUTO_INCREMENT, 
    titulo CHAR(100) UNIQUE, 
    descripcion MEDIUMTEXT, 
    ID_BLOQUE TINYINT, 
    FOREIGN KEY(ID_BLOQUE) REFERENCES BLOQUE(ID_BLOQUE) 
);

CREATE TABLE ASIGNACION(
    ID_ASIGN INT PRIMARY KEY AUTO_INCREMENT, 
    titulo CHAR(100), 
    indicaciones CHAR(255),
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    puntos INT, 
    fecha_asignacion DATETIME NOT NULL, 
    fecha_limite DATETIME NOT NULL, 
    ID_BLOQUE TINYINT, 
    FOREIGN KEY(ID_BLOQUE) REFERENCES BLOQUE(ID_BLOQUE), 
    ID_TEMA TINYINT, 
    FOREIGN KEY(ID_TEMA) REFERENCES TEMA(ID_TEMA), 
    rubrica MEDIUMTEXT 
    ID_AULA CHAR(50),
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    ID_TIPO_ASIGN TINYINT, 
    FOREIGN KEY(ID_TIPO_ASIGN) REFERENCES TIPO_ASIGN(ID_TIPO_ASIGN)
);

CREATE TABLE USER_HAS_ASIGNACION(
    ID_UHA INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO), 
    ID_ASIGN INT, 
    FOREIGN KEY(ID_ASIGN) REFERENCES ASIGNACION(ID_ASIGN), 
    ID_ESTADO_ENTREGA TINYINT, 
    FOREIGN KEY(ID_ESTADO_ENTREGA) REFERENCES ESTADO_ENTREGA(ID_ESTADO_ENTREGA),
    fecha_entrega DATETIME NOT NULL, 
    calificacion TINYINT, 
    texto_tarea CHAR(200)
);

CREATE TABLE ARCH_ENTREGA(
    ID_ARCH_ENTREGA INT PRIMARY KEY AUTO_INCREMENT, 
    nombre CHAR(250), 
    ruta_archivo CHAR(250),         
    tipo_extension CHAR(100),     
    ID_UHA INT, 
    FOREIGN KEY(ID_UHA) REFERENCES USER_HAS_ASIGNACION(ID_UHA)
);

CREATE TABLE LINKS_ASIGNACION(
    ID_LINKASIGN INT PRIMARY KEY AUTO_INCREMENT, 
    link CHAR(250), 
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA)
);
/**/

CREATE TABLE ARCH_ADJ_ASIGN(
    ID_ARCH_ADJ_ASIGN INT PRIMARY KEY AUTO_INCREMENT, 
    nombre CHAR(100), 
    ruta_arch CHAR(250), 
    tipo_arch CHAR(50), 
    ID_ASIGN INT, 
    FOREIGN KEY(ID_ASIGN) REFERENCES ASIGNACION(ID_ASIGN)
); 


CREATE TABLE COMENT_PRIV_ASIGN(
    ID_COMENT_PRIV_ASIGN INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO), 
    ID_UHA INT, 
    FOREIGN KEY(ID_UHA) REFERENCES USER_HAS_ASIGNACION(ID_UHA),
    comentario TEXT, 
    fecha_coment DATETIME NOT NULL 
);

CREATE TABLE COMENT_ASIGN(
    ID_COMENT_ASIGN INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_ASIGN INT, 
    FOREIGN KEY(ID_ASIGN) REFERENCES ASIGNACION(ID_ASIGN),
    comentario TEXT, 
    fecha_coment DATETIME NOT NULL
);

CREATE TABLE TIPO_JUEGO(
    ID_TIPO_JUEGO SMALLINT PRIMARY KEY AUTO_INCREMENT, 
    juego CHAR(75), 
    descripcion TEXT
);

CREATE TABLE JUEGO(
    ID_JUEGO SMALLINT PRIMARY KEY AUTO_INCREMENT, 
    ID_TIPO_JUEGO SMALLINT, 
    FOREIGN KEY(ID_TIPO_JUEGO) REFERENCES TIPO_JUEGO(ID_TIPO_JUEGO), 
    ID_TEMA TINYINT, 
    FOREIGN KEY(ID_TEMA) REFERENCES TEMA(ID_TEMA),
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    ID_BLOQUE TINYINT, 
    FOREIGN KEY(ID_BLOQUE) REFERENCES BLOQUE(ID_BLOQUE),
    nombre CHAR(50), 
    descripcion TEXT, 
    fecha_asignacion DATETIME NOT NULL,
    fecha_entrega DATETIME NOT NULL, 
    puntos INT 
);

CREATE TABLE USER_HAS_JUEGO(
    ID_UHJ INT PRIMARY KEY AUTO_INCREMENT, 
    ID_JUEGO SMALLINT, 
    FOREIGN KEY(ID_JUEGO) REFERENCES JUEGO(ID_JUEGO), 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO), 
    puntos_obt INT,
    posicion SMALLINT, 
    fecha_juego DATETIME NOT NULL
);


CREATE TABLE TIPO_CPUB(
    ID_TIPO_CPUB INT PRIMARY KEY AUTO_INCREMENT, 
    tipo CHAR(50), 
    key_word CHAR(50)
);

CREATE TABLE TIPO_MAT_CAMMAT(
    ID_TIPO_MAT_CAMMAT INT PRIMARY KEY AUTO_INCREMENT, 
    tipo_matcmmt CHAR(50)
);

CREATE TABLE PUB_CAM_MAT(
    ID_PUB_CMMT INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO), 
    ID_MATERIAS TINYINT, 
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS), 
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA), 
    ID_TIPO_CPUB INT, 
    FOREIGN KEY(ID_TIPO_CPUB) REFERENCES TIPO_CPUB(ID_TIPO_CPUB), 
    ID_TIPO_MAT_CAMMAT INT, 
    FOREIGN KEY(ID_TIPO_MAT_CAMMAT) REFERENCES TIPO_MAT_CAMMAT(ID_TIPO_MAT_CAMMAT), 
    link CHAR(250), /*En duda*/
    tema CHAR(250), 
    unidad SMALLINT, 
    descripcion TEXT, 
    fecha_creacion DATETIME NOT NULL, 
    fecha_especial DATETIME NOT NULL, 
    cam_cora INT, 
    cam_report INT

);

/*En duda, ¿Es PUB_CMMT o PUB_CmmT?*/
CREATE TABLE ARCH_ADJ_CAMMAT(
    ID_ARCH_ADJ_CAMMAT INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PUB_CMMT INT, 
    FOREIGN KEY(ID_PUB_CMMT) REFERENCES PUB_CAM_MAT(ID_PUB_CMMT), 
    nombre CHAR(50),
    tipo_arch CHAR(50), 
    ruta_arch CHAR(250)
);

CREATE TABLE USER_HAS_INTERESES_PUBCAMMAT(
    ID_UHI_PCMMT INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_PUB_CMMT INT, 
    FOREIGN KEY(ID_PUB_CMMT) REFERENCES PUB_CAM_MAT(ID_PUB_CMMT)
);

CREATE TABLE PCMMT_HAS_REPORT(
    ID_PCMMTHR INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_PUB_CMMT INT, 
    FOREIGN KEY(ID_PUB_CMMT) REFERENCES PUB_CAM_MAT(ID_PUB_CMMT), 
    motivo TEXT
);



CREATE TABLE ESTADO_PFORO(
    ID_ESTADO_PFORO TINYINT PRIMARY KEY AUTO_INCREMENT, 
    estado_foro VARCHAR(10)
);

CREATE TABLE TIPO_PUB_FORO(
    ID_TIPO_PFORO TINYINT PRIMARY KEY AUTO_INCREMENT, 
    tipo CHAR(50)
);

CREATE TABLE PUB_FORO(
    ID_PUB_FORO INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_MATERIAS TINYINT, 
    FOREIGN KEY(ID_MATERIAS) REFERENCES MATERIAS(ID_MATERIAS),
    ID_TIPO_PFORO TINYINT, 
    FOREIGN KEY(ID_TIPO_PFORO) REFERENCES TIPO_PUB_FORO(ID_TIPO_PFORO), 
    ID_ESTADO_PFORO TINYINT, 
    FOREIGN KEY(ID_ESTADO_PFORO) REFERENCES ESTADO_PFORO(ID_ESTADO_PFORO),
    pregunta TEXT, 
    desarrollo TEXT, 
    fecha_creacion DATETIME NOT NULL,
    link CHAR(250)
);

CREATE TABLE RESP_PFORO(
    ID_RESP_PFORO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_PUB_FORO INT, 
    FOREIGN KEY(ID_PUB_FORO) REFERENCES PUB_FORO(ID_PUB_FORO),
    fecha_resp DATETIME NOT NULL, 
    respuesta TEXT
);

CREATE TABLE ARCH_RESP_FORO(
    ID_ARCH_R_PFORO INT PRIMARY KEY AUTO_INCREMENT,
    ID_RESP_PFORO INT, 
    FOREIGN KEY(ID_RESP_PFORO) REFERENCES RESP_PFORO(ID_RESP_PFORO),
    nombre CHAR(50),
    tipo_arch CHAR(250),
    ruta_arch CHAR(250)
);

CREATE TABLE PFORO_HAS_REPORT(
    ID_UHR_PFORO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_PUB_FORO INT, 
    FOREIGN KEY(ID_PUB_FORO) REFERENCES PUB_FORO(ID_PUB_FORO),
    motivo TEXT
);

/*------------------------------------------------------------------------------------------------------*/
/*ERRRRROR*/
CREATE TABLE ARCH_PFORO(
    ID_ARCH_PFORO INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PUB_FORO INT, 
    FOREIGN KEY(ID_PUB_FORO) REFERENCES PUB_FORO(ID_PUB_FORO),
    nombre CHAR(100), 
    tipo_arch CHAR(50), 
    ruta_arch CHAR(250)
);

CREATE USER_HAS_INTERES_PFORO(
    ID_UHI_PFORO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_PUB_FORO INT, 
    FOREIGN KEY(ID_PUB_FORO) REFERENCES PUB_FORO(ID_PUB_FORO), 
    ver_bool BOOLEAN 
);

CREATE TABLE RESP_RPFORO(
    ID_RESP_RPFORO INT PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_RESP_PFORO INT, 
    FOREIGN KEY(ID_RESP_PFORO) REFERENCES RESP_PFORO(ID_RESP_PFORO), 
    fecha_resp DATETIME NOT NULL, 
    respuesta TEXT 
);


CREATE TABLE TIPO_EVENT(
    ID_TIPO_EVENT TINYINT PRIMARY KEY AUTO_INCREMENT,
    ID_PRIV TINYINT, 
    FOREIGN KEY(ID_PRIV) REFERENCES PRIVACIDAD(ID_PRIV), 
    tipo CHAR(100), 
    descripcion TEXT 
);


CREATE TABLE MES(
    ID_MES TINYINT PRIMARY KEY AUTO_INCREMENT, 
    mes VARCHAR(30)
);

CREATE TABLE MES_FIN(
    ID_MES_FIN TINYINT PRIMARY KEY AUTO_INCREMENT, 
    mes_fin VARCHAR(30)
);

CREATE TABLE EVENTOS_REPEAT(
    ID_EVENTO_R SMALLINT PRIMARY KEY AUTO_INCREMENT,
    ID_TIPO_EVENT TINYINT DEFAULT[7],
    FOREIGN KEY(ID_TIPO_EVENT) REFERENCES TIPO_EVENT(ID_TIPO_EVENT),
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA), 
    titulo CHAR(250), 
    descripcion TEXT
);

CREATE TABLE DIA_SEMANA(
    ID_DIA_SEMANA TINYINT PRIMARY KEY AUTO_INCREMENT, 
    dia CHAR(25) 
);

CREATE TABLE EVENTO_R_HAS_DIADESEMANA(
    ID_E_RDHS SMALLINT PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO_R SMALLINT, 
    FOREIGN KEY(ID_EVENTO_R) REFERENCES EVENTOS_REPEAT(ID_EVENTO_R),
    ID_DIA_SEMANA TINYINT, 
    FOREIGN KEY(ID_DIA_SEMANA) REFERENCES DIA_SEMANA(ID_DIA_SEMANA), 
    hora_inicio TIME NOT NULL, 
    hora_final TIME NOT NULL
);

CREATE TABLE EVENTOS(
    ID_EVENTO SMALLINT PRIMARY KEY AUTO_INCREMENT, 
    ID_TIPO_EVENT TINYINT, 
    FOREIGN KEY(ID_TIPO_EVENT) REFERENCES TIPO_EVENT(ID_TIPO_EVENT), 
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_ASIGN INT, 
    FOREIGN KEY(ID_ASIGN) REFERENCES ASIGNACION(ID_ASIGN),
    ID_MES TINYINT, 
    FOREIGN KEY(ID_MES) REFERENCES MES(ID_MES), 
    ID_CICLOS SMALLINT, 
    FOREIGN KEY(ID_CICLOS) REFERENCES CICLOS(ID_CICLOS), 
    hora_inicio TIME NOT NULL, 
    hora_final TIME NOT NULL, 
    dia CHAR(25), 
    año INT, 
    fecha_comp DATETIME NOT NULL, 
    key_word CHAR(100), 
    titulo CHAR(250), 
    descripcion TEXT
);

CREATE TABLE EVENTOS_RANG(
    ID_EVENTO_RANG INT PRIMARY KEY AUTO_INCREMENT,  
    ID_TIPO_EVENT TINYINT, 
    FOREIGN KEY(ID_TIPO_EVENT) REFERENCES TIPO_EVENT(ID_TIPO_EVENT), 
    ID_AULA CHAR(50), 
    FOREIGN KEY(ID_AULA) REFERENCES AULA(ID_AULA),
    ID_USUARIO INT, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    ID_ASIGN INT, 
    FOREIGN KEY(ID_ASIGN) REFERENCES ASIGNACION(ID_ASIGN),
    ID_MES TINYINT, 
    FOREIGN KEY(ID_MES) REFERENCES MES(ID_MES), 
    ID_MES_FIN TINYINT, 
    FOREIGN KEY(ID_MES_FIN) REFERENCES MES_FIN(ID_MES_FIN),
    ID_CICLOS SMALLINT, 
    FOREIGN KEY(ID_CICLOS) REFERENCES CICLOS(ID_CICLOS),
    hora_inicio TIME NOT NULL, 
    hora_final TIME NOT NULL, 
    dia CHAR(25), 
    año INT, 
    fecha_comp DATETIME NOT NULL, 
    dia_fin CHAR(50), 
    fecha_comp_fin DATETIME NOT NULL, 
    key_word CHAR(100), 
    titulo CHAR(250), 
    descripcion TEXT
);





