

INSERT INTO MATERIAS VALUES
        (0, 'Lógica', 4, 5), 
        (0, 'Geografía', 4, 5), 
        (0, 'Dibujo II', 4, 5),
        (0, 'Lengua extranjera Inglés IV', 4, 5), 
        (0, 'Lengua extranjera Francés IV', 4, 5), 
        (0, 'Danza clásica', 4, 6), 
        (0, 'Danza contemporánea', 4, 6), 
        (0, 'Danza española', 4, 6), 
        (0, 'Danza regional mexicana', 4, 6), 
        (0, 'Escultura IV', 4, 6), 
        (0, 'Fotografía IV', 4, 6), 
        (0, 'Grabado IV', 4, 6), 
        (0, 'Música IV', 4, 6), 
        (0, 'Pintura IV', 4, 6), 
        (0, 'Teatro IV', 4, 6),
        (0, 'Educación Física IV', 4, 5), 
        (0, 'Orientación Educativa IV', 4, 5), 
        (0, 'Informática', 4, 5),
        (0, 'Matemáticas V', 5, 5), 
        (0, 'Química III', 5, 5), 
        (0, 'Biología IV', 5, 5), 
        (0, 'Educación para la Salud', 5, 5), 
        (0, 'Historia de México II', 5, 5), 
        (0, 'Etimologías Grecolatinas', 5, 5), 
        (0, 'Lengua extranjera Inglés V', 5, 5), 
        (0, 'Lengua extranjera Francés V', 5, 5),
        (0, 'Lengua extranjera Italiano V', 5, 5), 
        (0, 'Lengua extranjera Alemán V', 5, 5), 
        (0, 'Lengua extranjera Inglés I', 5, 5), 
        (0, 'Lengua extranjera Francés I', 5, 5),
        (0, 'Lengua extranjera Italiano I', 5, 5), 
        (0, 'Lengua extranjera Alemán I', 5, 5), 
        (0, 'Ética', 5, 5), 
        (0, 'Educación Física V', 5, 5),
        (0, 'Danza clásica', 5, 6), 
        (0, 'Danza contemporánea', 5, 6), 
        (0, 'Danza española', 5, 6), 
        (0, 'Danza regional mexicana', 5, 6), 
        (0, 'Escultura V', 5, 6), 
        (0, 'Fotografía V', 5, 6), 
        (0, 'Grabado V', 5, 6), 
        (0, 'Música V', 5, 6), 
        (0, 'Pintura V', 5, 6), 
        (0, 'Teatro V', 5, 6),
        (0, 'Orientación Educativa V', 5, 5),
        (0, 'Literatura Universal', 5, 5),
        (0, 'Derecho', 6, 5), 
        (0, 'Literatura Mex. e Iberoam', 6, 5), 
        (0, 'Inglés VI', 6, 5), 
        (0, 'Francés VI', 6, 5), 
        (0, 'Alemán II', 6, 5), 
        (0, 'Italiano II', 6, 5), 
        (0, 'Inglés II', 6, 5), 
        (0, 'Francés II', 6, 5), 
        (0, 'Psicología', 6, 5), 
        (0, 'Higiene Mental', 6, 5), 
        (0, 'Estadística y probabilidad', 6, 5), 
        (0, 'Matemáticas VI', 6, 5), 
        (0, 'Dibujo constructivo II', 6, 1), 
        (0, 'Física IV-A1', 6, 1),
        (0, 'Química IV-A1', 6, 1),
        (0, 'Geología y Mineralogía', 6, 1),
        (0, 'Biología V', 6, 2), 
        (0, 'Física IV-A2', 6, 2),
        (0, 'Química IV-A2', 6, 2),
        (0, 'Geografía Económica', 6, 3), 
        (0, 'Introducc. Al estudio de las Ciencias Sociales y Ec', 6, 3),  
        (0, 'Problemas Soc.Polit y Económicos de México', 6, 3), 
        (0, 'Contabilidad y Gestión Administrativa', 6, 3),  
        (0, 'Historia de la Cultura', 6, 4), 
        (0, 'Historia de las Doctrinas Filosóficas', 6, 4),  
        (0, 'Modelado II', 6, 4), 
        (0, 'Estética', 6, 4), 
        (0, 'Historia del Arte', 6, 4), 
        (0, 'Temas selec. Biología', 6, 7), 
        (0, 'Temas selec. de Morfología y Fisiología', 6, 7), 
        (0, 'Físico-Química', 6, 7), 
        (0, 'Temas selec. Matemáticas', 6, 7), 
        (0, 'Informática aplicada a la Ciencia y la Industria', 6, 7),
        (0, 'Astronomía', 6, 7),
        (0, 'Literatura mexicana', 6, 7),
        (0, 'Revolución Mexicana', 6, 7),
        (0, 'Geografía Política', 6, 7), 
        (0, 'Sociología', 6, 7), 
        (0, 'Comunicación Visual', 6, 7), 
        (0, 'Pensamiento Filosófico de México', 6, 4), 
        (0, 'Latín', 6, 4), 
        (0, 'Griego', 6, 4), 

        


        

        



         



